version: '3'

networks:
    dev_network:
        name: dev_network

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    networks: 
      - dev_network
    command: /bin/sh -c "while sleep 1000; do :; done"

  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:        
        VARIANT: 11
        INSTALL_MAVEN: "true"
        INSTALL_GRADLE: "false"
        NODE_VERSION: "lts/*"

    depends_on:      
      - db   
    networks: 
      - dev_network      
    init: true
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspace
